# Generated by Django 2.2.4 on 2019-08-14 15:10

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the full name', max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'User Comment',
                'verbose_name_plural': 'User Comments',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Separate with comma if more than 1', max_length=1000, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Separate with comma if more than 1', max_length=1000, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Our Contact Detail',
                'verbose_name_plural': 'Our Contact Details',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsheading', models.CharField(max_length=1000, verbose_name='News Heading')),
                ('newscontent', froala_editor.fields.FroalaField(default='', max_length=10000, verbose_name='News Content')),
                ('newsdate', models.DateField(auto_now=True)),
                ('newspicture', models.ImageField(blank=True, default='../../static/greencare/images/4.jpg', help_text='this field is optional', null=True, upload_to='news/', verbose_name='Attached Image')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the full name', max_length=200, verbose_name='Full Name')),
                ('position', models.CharField(max_length=1000, verbose_name='Position')),
                ('picture', models.ImageField(max_length=1000, upload_to='ourteam/', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Our Team',
                'verbose_name_plural': 'Our Team',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='enter the name of the service', max_length=200, verbose_name='Name Of Service')),
                ('slug', models.SlugField(unique=True)),
                ('button_text', models.CharField(default='Hire Us', help_text='text to appear on the button', max_length=200, verbose_name='Button Text')),
                ('description', froala_editor.fields.FroalaField(blank=True, default='', max_length=10000, null=True, verbose_name='Service Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'index_together': {('id', 'service_name')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaName', models.CharField(max_length=200, verbose_name='Name Of Media')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termsconditions', froala_editor.fields.FroalaField(default='', max_length=10000, verbose_name='Terms And Conditions')),
                ('nameofservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greencare.Service', verbose_name='Name Of Service')),
            ],
            options={
                'verbose_name': 'Terms And Condition',
                'verbose_name_plural': 'Terms And Conditions',
            },
        ),
        migrations.CreateModel(
            name='ServicesDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phoneNumber', models.CharField(help_text='the phone number we shall reach you on', max_length=13, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='this field is optional', max_length=254, null=True)),
                ('description', froala_editor.fields.FroalaField(blank=True, default='', max_length=20000, null=True, verbose_name='Description of what you require')),
                ('accepttermsconditions', models.BooleanField(default='True')),
                ('nameofservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greencare.Service', verbose_name='Name Of Service')),
            ],
            options={
                'verbose_name': 'Service Deals',
                'verbose_name_plural': 'Service Deals',
            },
        ),
    ]
