# Generated by Django 2.2.4 on 2019-08-14 15:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
