# Generated by Django 2.2.4 on 2019-08-14 16:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0002_auto_20190814_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newscontent',
            field=tinymce.models.HTMLField(default='', verbose_name='News Content'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='News Content'),
        ),
        migrations.AlterField(
            model_name='servicesdeals',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Description of what you require'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='termsconditions',
            field=tinymce.models.HTMLField(default='', verbose_name='Terms And Conditions'),
        ),
    ]
