# Generated by Django 2.2.4 on 2019-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0003_auto_20190814_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='', verbose_name='News Content'),
        ),
    ]
