# Generated by Django 2.2.4 on 2019-08-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0004_auto_20190814_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='Title Of The Experience')),
                ('detail', models.TextField(verbose_name='The Actual Detailed Experience')),
                ('imageattached', models.ImageField(blank=True, default='', help_text='this field is optional', null=True, upload_to='experience/', verbose_name='Attached Image')),
            ],
            options={
                'verbose_name': 'Our Experience',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='newscontent',
            field=models.TextField(default='', verbose_name='News Content'),
        ),
        migrations.AlterField(
            model_name='servicesdeals',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of what you require'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='termsconditions',
            field=models.TextField(default='', verbose_name='Terms And Conditions'),
        ),
    ]
