# Generated by Django 2.2.4 on 2019-10-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0005_auto_20190821_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetitle', models.CharField(max_length=200, verbose_name='Service Title')),
                ('servicedetail', models.TextField(verbose_name='Service Details')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseOurAgroServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=1000, upload_to='why-choose-us/', verbose_name='Picture')),
                ('heading', models.CharField(max_length=200, verbose_name='Heading')),
                ('subheading', models.CharField(default='', max_length=200, verbose_name='Sub Heading')),
                ('detail', models.TextField(default='', verbose_name='Detail')),
            ],
        ),
    ]
