# Generated by Django 2.2.4 on 2019-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0006_agroservices_whychooseouragroservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseouragroservices',
            name='subheading',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Sub Heading'),
        ),
    ]
