# Generated by Django 2.2.4 on 2019-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0008_auto_20191009_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the full name', max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
