# Generated by Django 2.2.4 on 2019-10-09 11:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0009_auto_20191009_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Optional', max_length=31, null=True),
        ),
    ]
