# Generated by Django 2.2.4 on 2019-10-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0011_auto_20191009_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Article',
        ),
    ]
