# Generated by Django 2.2.4 on 2019-10-09 13:24

from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('greencare', '0012_auto_20191009_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('service_name', models.CharField(help_text='enter the name of the service', max_length=200, verbose_name='Name Of Service')),
                ('slug', models.SlugField(unique=True)),
                ('button_text', models.CharField(default='Hire Us', help_text='text to appear on the button', max_length=200, verbose_name='Button Text')),
                ('description', models.TextField(default='', verbose_name='News Content')),
            ],
            options={
                'verbose_name': 'Agro Service',
                'verbose_name_plural': 'Agro Services',
                'index_together': {('id', 'service_name')},
            },
        ),
    ]
